// TODO: delete this file
import { Player, PlayerPublic } from "../../types";
import { fakeDiceRolls } from "./fake-dice";

export const fakePlayers: PlayerPublic[] = [
  {
    userId: "1",
    username: "umpalumpa",
    avatarId: 1,
    diceAmount: 10,
    powerUpsAmount: 9,
    isConnected: false,
    isReady: false,
    isActive: false,
    hasInitialPowerUps: true,
    hasRolledDice: true,
  },
  {
    userId: "2",
    username: "señor.garfio",
    avatarId: 2,
    diceAmount: 10,
    powerUpsAmount: 9,
    isConnected: false,
    isReady: false,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    isActive: false,
  },
  {
    userId: "3",
    username: "shake.it",
    avatarId: 3,
    diceAmount: 10,
    powerUpsAmount: 9,
    isConnected: false,
    isReady: false,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    isActive: false,
  },
  {
    userId: "4",
    username: "something.great",
    avatarId: 4,
    diceAmount: 10,
    powerUpsAmount: 9,
    isConnected: false,
    isReady: false,
    hasInitialPowerUps: true,
    hasRolledDice: true,

    isActive: false,
  },
  {
    userId: "5",
    username: "god",
    avatarId: 5,
    diceAmount: 10,
    powerUpsAmount: 9,
    isConnected: false,
    isReady: false,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    isActive: false,
  },
  {
    userId: "6",
    username: "lekker",
    avatarId: 6,
    diceAmount: 10,
    powerUpsAmount: 9,
    isConnected: false,
    isReady: false,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    isActive: false,
  },
];

export const fakeLocalPlayer: Player = {
  powerUpIds: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
  userId: "7",
  username: "too cool",
  avatarId: 7,
  diceAmount: 10,
  powerUpsAmount: 9,
  isConnected: false,
  isReady: false,
  hasInitialPowerUps: true,
  hasRolledDice: true,
  diceValue: fakeDiceRolls,
  isActive: false,
};
