import { PlayerPublic } from "../../types";

export const fakePlayers: PlayerPublic[] = [
  {
    userId: "000000000000000000000000000000000000",
    username: "umpalumpa",
    diceAmount: 5,
    powerUpsAmount: 3,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    avatarId: 1,
    isConnected: true,
    isReady: false,
    isActive: true,
    status: "playing",
    actionRole: undefined,
    isTarget: false,
    extraDice: 0,
    arePowerUpsDisabled: false,
  },
  {
    userId: "000000000000000000000000000000000001",
    username: "señor.garfio",
    diceAmount: 5,
    powerUpsAmount: 3,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    avatarId: 2,
    isConnected: false,
    isReady: false,
    isActive: false,
    status: "playing",
    actionRole: undefined,
    isTarget: false,
    extraDice: 0,
    arePowerUpsDisabled: false,
  },
  {
    userId: "000000000000000000000000000000000002",
    username: "shake.it",
    diceAmount: 5,
    powerUpsAmount: 3,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    avatarId: 3,
    isConnected: true,
    isReady: false,
    isActive: false,
    status: "playing",
    actionRole: undefined,
    isTarget: false,
    extraDice: 0,
    arePowerUpsDisabled: false,
  },
  {
    userId: "000000000000000000000000000000000003",
    username: "something.great",
    diceAmount: 5,
    powerUpsAmount: 3,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    avatarId: 4,
    isConnected: false,
    isReady: false,
    isActive: false,
    status: "playing",
    actionRole: undefined,
    isTarget: false,
    extraDice: 0,
    arePowerUpsDisabled: false,
  },
  {
    userId: "000000000000000000000000000000000004",
    username: "god",
    diceAmount: 5,
    powerUpsAmount: 3,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    avatarId: 5,
    isConnected: true,
    isReady: false,
    isActive: false,
    status: "playing",
    actionRole: undefined,
    isTarget: false,
    extraDice: 0,
    arePowerUpsDisabled: false,
  },
  {
    userId: "000000000000000000000000000000000005",
    username: "lekker",
    diceAmount: 5,
    powerUpsAmount: 3,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    avatarId: 6,
    isConnected: false,
    isReady: false,
    isActive: false,
    status: "playing",
    actionRole: undefined,
    isTarget: false,
    extraDice: 0,
    arePowerUpsDisabled: false,
  },
];
