import { PlayerPublic } from "../../types";

export const fakePlayers: PlayerPublic[] = [
  {
    userId: "000000000",
    username: "umpalumpa",
    diceAmount: 5,
    powerUpsAmount: 3,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    avatarId: 1,
    isConnected: true,
    isReady: false,
  },
  {
    userId: "11111111",
    username: "señor.garfio",
    diceAmount: 5,
    powerUpsAmount: 3,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    avatarId: 2,
    isConnected: false,
    isReady: false,
  },
  {
    userId: "2222222",
    username: "shake.it",
    diceAmount: 5,
    powerUpsAmount: 3,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    avatarId: 3,
    isConnected: true,
    isReady: false,
  },
  {
    userId: "33333",
    username: "something.great",
    diceAmount: 5,
    powerUpsAmount: 3,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    avatarId: 4,
    isConnected: false,
    isReady: false,
  },
  {
    userId: "44444",
    username: "god",
    diceAmount: 5,
    powerUpsAmount: 3,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    avatarId: 5,
    isConnected: true,
    isReady: false,
  },
  {
    userId: "55555",
    username: "lekker",
    diceAmount: 5,
    powerUpsAmount: 3,
    hasInitialPowerUps: true,
    hasRolledDice: true,
    avatarId: 6,
    isConnected: false,
    isReady: false,
  },
];
