apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    # nginx.ingress.kubernetes.io/stream-snippet: |
    #   server {
    #     listen 8000;
    #     proxy_pass 127.0.0.1:80;
    #   }
    nginx.ingress.kubernetes.io/stream-snippet: |
      # Nakama HTTP API.
      server {
        # listen 80 ssl;
        # listen [::]:80 ssl;
        listen 80;
        listen [::]:80;

        # Domain names this server should respond to.
        # server_name api.liars-dice.staging.kryha.dev;

        # SSL certificate configuration.
        # ssl_certificate         /etc/letsencrypt/live/nakama/fullchain.pem;
        # ssl_certificate_key     /etc/letsencrypt/live/nakama/privkey.pem;
        # ssl_trusted_certificate /etc/letsencrypt/live/nakama/chain.pem;
        # ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

        # location / {
          # Enable CORS from anywhere with support for pre-flight requests.
          # See: https://enable-cors.org/server_nginx.html
          # if ($request_method = 'OPTIONS') {
          #   add_header 'Access-Control-Allow-Origin' '*';
          #   add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
          #   add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
          #   # Tell client that this pre-flight info is valid for 20 days
          #   add_header 'Access-Control-Max-Age' 1728000;
          #   add_header 'Content-Type' 'text/plain; charset=utf-8';
          #   add_header 'Content-Length' 0;
          #   return 204;
          # }
          # if ($request_method = 'POST') {
          #   add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
          #   add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
          #   add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
          # }
          # if ($request_method = 'GET') {
            # add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            # add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
            # add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
          # }

          proxy_pass 127.0.0.1:7350;
        # }

        # location /ws {
        #   # Enable CORS from anywhere with support for pre-flight requests.
        #   # See: https://enable-cors.org/server_nginx.html
        #   if ($request_method = 'OPTIONS') {
        #     add_header 'Access-Control-Allow-Origin' '*';
        #     add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        #     add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
        #     # Tell client that this pre-flight info is valid for 20 days
        #     add_header 'Access-Control-Max-Age' 1728000;
        #     add_header 'Content-Type' 'text/plain; charset=utf-8';
        #     add_header 'Content-Length' 0;
        #     return 204;
        #   }
        #   if ($request_method = 'POST') {
        #     add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        #     add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
        #     add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        #   }
        #   if ($request_method = 'GET') {
        #     add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        #     add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
        #     add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        #   }

        #   # proxy_pass http://nakama:7350/ws;
        #   # proxy_http_version 1.1;
        #   # proxy_set_header Upgrade $http_upgrade;
        #   # proxy_set_header Connection "Upgrade";
        # }
      }
spec:
  tls:
    - secretName: "backend.liars-dice.staging.kryha.dev"
      hosts:
        - "backend.liars-dice.staging.kryha.dev"
    - secretName: "api.liars-dice.staging.kryha.dev"
      hosts:
        - "api.liars-dice.staging.kryha.dev"
  rules:
    - host: "backend.liars-dice.staging.kryha.dev"
      http:
        paths:
          - path: "/(.*)"
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  name: dashboard
    - host: "api.liars-dice.staging.kryha.dev"
      http:
        paths:
          - path: "/(.*)"
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: api
