apiVersion: skaffold/v3
kind: Config
metadata:
  name: boloney
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
    push: true
  artifacts:
    - image: eu.gcr.io/web3-335312/aleo/boloney-production/frontend
      docker:
        dockerfile: Dockerfile.frontend
        buildArgs:
          VITE_ENV: production
          VITE_BACKEND_URL: backend.boloney.io
          VITE_API_URL: api.boloney.io
          VITE_USE_SSL: "true"
          VITE_API_PORT: "443"
          VITE_GA_TRACKING_ID: "G-8MLWBJTD89"
          VITE_TOOLKIT_URL: https://zk-gaming-tk.staging.kryha.dev
          VITE_ZK_ENABLED: "true"
    - image: eu.gcr.io/web3-335312/aleo/boloney-production/backend
      docker:
        dockerfile: Dockerfile.backend
manifests:
  kustomize:
    paths:
      - ./deployment/production/workloads
deploy:
  kubectl: {}
