apiVersion: skaffold/v3
kind: Config
metadata:
  name: boloney
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
    push: true
  artifacts:
    - image: eu.gcr.io/web3-335312/aleo/boloney/frontend
      docker:
        dockerfile: Dockerfile.frontend
        buildArgs:
          VITE_BACKEND_URL: backend.boloney.staging.kryha.dev
          VITE_API_URL: api.boloney.staging.kryha.dev
          VITE_USE_SSL: true
          VITE_API_PORT: "443"
    - image: eu.gcr.io/web3-335312/aleo/boloney/backend
      docker:
        dockerfile: Dockerfile.backend
manifests:
  kustomize:
    paths:
      - ./deployment/staging/workloads
deploy:
  kubectl: {}
