apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: liars-dice
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
    push: true
  artifacts:
    - image: eu.gcr.io/web3-335312/aleo/liars-dice/frontend
      docker:
        dockerfile: Dockerfile.frontend
        buildArgs:
          VITE_BACKEND_URL: https://backend.liars-dice.staging.kryha.dev
          VITE_API_URL: https://api.liars-dice.staging.kryha.dev
    - image: eu.gcr.io/web3-335312/aleo/liars-dice/backend
      docker:
        dockerfile: Dockerfile.backend
deploy:
  kustomize:
    paths:
      - ./deployment/staging/workloads
    defaultNamespace: liars-dice-staging
