apiVersion: skaffold/v3
kind: Config
metadata:
  name: boloney
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
  artifacts:
    - image: frontend
      docker:
        dockerfile: Dockerfile.frontend
    - image: backend
      docker:
        dockerfile: Dockerfile.backend
manifests:
  kustomize:
    paths:
      - ./deployment/local/workloads
deploy:
  kubectl: {}
