console:
  max_message_size_bytes: 409600
logger:
  level: "info"
runtime:
  js_entrypoint: "build/index.js"
session:
  token_expiry_sec: 86400 # 24 hours
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072
