apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 7349
      targetPort: 7349
      protocol: TCP
      name: util-0
    - port: 7350
      targetPort: 7350
      protocol: TCP
      name: api
    - port: 7351
      targetPort: 7351
      protocol: TCP
      name: dashboard
