apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 300m
              memory: 128Mi
            limits:
              memory: 1024Mi
              cpu: "2"
          ports:
            - containerPort: 80
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FRONTEND_NAME
              value: "FRONTEND"
            - name: PORT
              value: "80"
