export const contact = {
  contactUs: "contact us",
  alreadyPlayed: "already played the game?",
  tellUsAboutYourExperience: "tell us about your experience",
  shareFeedback: "share feedback",
  spottedBug: "spotted a bug?",
  tellUsAboutBug: "tell us about it, so we can take care of it as fast as possible.",
  reportBug: "report a bug",
  wantToSayHi: "want to say hi?",
  letsChat: "let's chat! Send us an email and let's keep in touch.",
  doYouHaveQuestions: "do you have business enquiries or general questions?",
  sendEmail: "send us an e-mail",
  boloneyHelpEmail: "boloney@kryha.io",
  importantThings: "important things",
  comeSayHi: "come say hi",
  privacyPolicy: "privacy policy",
  termsAndConditions: "terms & conditions",
  generalTermsAndConditions: "general terms and conditions",
};
