export const general = {
  chat: "chat",
  history: "history",
  matchSettings: "match settings",
  logout: "logout",
  leaveMatch: "leave match",
  defaultTime: "0:00",
  amount: "amount",
  pips: "pips",
  logoHere: "logo here",
  rules: "rules",
  menu: "menu",
  info: "info",
  connected: "connected",
  waiting: "waiting",
  waitingForTheOthersToBeReady: "waiting for the others to be ready...",
  appName: "Boloney",
  gameCreated: "game created!",
  yourGameHasBeenCreated:
    "your match has been successfully created! Now you can share it with your friends using the link below. Have fun!",
  onlyPlayersWithThisCode: "only players with this code are able to join the match.",
  goToLobby: "go to lobby",
  ready: "ready",
  imReady: "i'm ready!",
  loading: "loading...",
  close: "close",
  goBack: "go back",
  // TODO: delete
  toolTipInfo: "this is the description",
  toolTipTitle: "this is the title",
  yourDice: "your dice",
};
