export const general = {
  chat: "chat",
  history: "history",
  settings: "settings",
  logout: "logout",
  exit: "exit",
  defaultTime: "0:00",
  amount: "amount",
  pips: "pips",
  logoHere: "logo here",
  rules: "rules",
  menu: "menu",
  info: "info",
  connected: "connected",
  waiting: "waiting",
  waitingForTheOthersToJoin: "waiting for the others to join...",
  appName: "Boloney",
  gameCreated: "game created!",
  yourGameHasBeenCreated: "your game has been successfully created! Now you can share it with your friends using the link below. Have fun!",
  onlyPlayersWithThisCode: "only players with this code are able to join the match.",
  goToLobby: "go to lobby",
  startGame: "start game",
};
