export const match = {
  currentlyAtStage: "stage",
  inXAmountOfRounds: "in",
  nextDrawRound: "draw in ",
  // TODO: delete these placeholders
  getPowerUps: "get power ups",
  goForIt: "go for it",
  rollDice: "roll dice",
  playerTurns: "player turns",
  endOfRound: "end of round",
  endOfMatch: "end of match",
  newMatch: "new match/create match",
  placeBid: "place bid",
  callExact: "call exact",
  callBoloney: "call boloney",
  whatsYourNextMove: "what's your next move hot shot?",
  timeToPickUpAStrategy: "time to pick a strategy, go forth and conquer!",
  takeAction: "take action",
  or: "or...",
  powerUp: "power-up",
  healDice: "heal dice",
  bid: "bid",
  boloney: "boloney",
  exact: "exact",
  timeToWait: "time to wait...",
  matchSettings: "match settings",
  players: "players",
  dicePP: "dice pp",
  powerUpPP: "power-up pp",
  extraPowerUp: "extra power-up",
  healAction: "heal action",
  powerUpTypeOnTheTable: "power-up type on the table",
  imReady: "im ready",
};
