export const match = {
  currentlyAtStage: "stage",
  inXAmountOfRounds: "in",
  nextDrawRound: "draw in ",
  // TODO: remove goForIt palceholder
  goForIt: "go for it",
  callExact: "call exact",
  callBoloney: "call boloney",
  whatsYourNextMove: "what's your next move, hotshot?",
  makeYourClaim: "make your claim",
  goOnShowThem: "go on, show them what you’re made of",
  takeAction: "take action",
  or: "or...",
  dead: "dead",
  powerUp: "power-up",
  healDice: "heal a die",
  bid: "bid",
  boloney: "boloney!",
  exact: "exact",
  matchSettings: "match settings",
  players: "players",
  dice: "dice",
  powerUpPP: "power-up pp",
  extraPowerUp: "extra power-up",
  healAction: "heal action",
  powerUpTypeOnTheTable: "power-up type on the table",
  homePage: "homepage",
  findOutYourPips: "time to reveal your pips for this round. Oh, the suspense…",
  getDice: "get your dice!",
  rollingYourDice: "wait for dice to be rolled!",
  drawRoundOffset: "draw round offset",
};
