export const playerTurn = {
  back: "back",
  boloney: "boloney!",
  callBoloney: "call boloney!",
  continueWithAction: "continue",
  letsSeeWhoIsRight: "let's see who is right...",
  itsTequilaUnderTheBridge: "it's tequila under the bridge...",
  youHaveWon: "you've won!",
  youHaveLost: "you've lost!",
  youDied: "you died!",
  youRock: "you rock at calling Boloney!",
  youSuck: "you suck at calling Boloney... you lose a dice!",
  waitingTime: "waiting time",
  weHaveAWinner: "we have a winner!",
  winner: "winner!",
  loser: "loser!",
  outOfTime: "out of time!",
  playerTimeOut: "time is out!",
  youRunOutOfTime: "you run out of time. We skip your turn and you lose a die!",
  youCanBreath: "you can breathe, your ass is safe!",
  exact: "exact",
  callExact: "call Exact!",
  areYouSureYouWantToCallExact: "are you sure you want to call exact on the last bid?",
  youSuckCallingExact: "you suck at calling Exact... you lose a dice!",
  areYouSureYouWantToCallBoloney: "are you sure you want to call Boloney?",
  placeBid: "add your bid",
  guess: "what is your guess?",
  itsTimeToThinkOutLoud: "time to think out loud, go forth and conquer!",
  getDiceBack: "get a die back!",
  lostAllDice: "your last die is gone, you are out of the game.\nStay tuned and see how the match ends.",
};
