export const playerTurn = {
  back: "back",
  boloney: "boloney!",
  callBoloney: "smell a bluff?",
  continueWithAction: "continue",
  letsSeeWhoIsRight: "let's see who is right...",
  youHaveWon: "you've won!",
  youHaveLost: "you've lost!",
  youDied: "you’re dead!",
  youRock: "you rock at calling Boloney!",
  badTimeCallingBoloney: "bad time to call Boloney!... you lose a die",
  waitingTime: "waiting time",
  roundEnded: "round ended!",
  winner: "winner!",
  loser: "loser!",
  outOfTime: "out of time!",
  playerTimeOut: "time is out!",
  youRunOutOfTime: "you run out of time. We skip your turn and you lose a die!",
  youAreRocking: "you are rocking it!",
  exact: "exact",
  callExact: "call Exact!",
  areYouSureYouWantToCallExact: "you sure you wanna call Exact on this bid?",
  youSuckCallingExact: "bad luck with your Exact call... you lose a die",
  placeBid: "add your bid",
  makeYourClaim: "make your claim",
  bidOnValue: "bid on the value that’s on the table. Use those spidey senses. You got this",
  lostAllDice: "you’ve lost all your dice, so you’re out of the game. Stick around to see how it ends!",
  feelThePower: "feel the power",
  healDiceSecondaryView: "i’m back, baby!",
  bidSecondaryView: "make your claim",
  boloneySecondaryView: "smell a bluff?",
  exactSecondaryView: "on the money",
  badTimeToBluff: "bad time to bluff!... you lose a die",
  youCanBreath: "you can breath for now...",
  iAmBack: "i’m back, baby!",
  choose5PowerUps: "choose 5 power-ups to exchange for 1 sweet, sweet die. Get it back!",
  healDice: "heal dice",
  whoGetsIt: "who’s gonna get it?",
  whatsYourGuess: "what’s your guess? Time to think out loud, go forth and conquer!",
  badLuckWithYourMove: "bad luck with your move...",
  totalSumIs: "the total sum of the dice is...",
  againstWho: "against who?",
  findHiddenPowerUps: "find their hidden power-ups!",
  whichOneToSteal: "which one do you want to steal?",
  getExtraPowerUps: "get 2 extra power-ups!",
  findExtraPowerUps: "find your 2 new extra power-ups!",
  itsTimeToThinkOutLoud: "time to think out loud, go forth and conquer!",
  getDiceBack: "get a die back!",
  youRockAtExact: "nice one on calling Exact!",
  randomMessages: [
    "hold your piglets",
    "reign in your Raccoons",
    "calm your Koalas",
    "settle your Sea Urchins",
    "cool your Sea Cucumbers",
    "soothe your Sasquatches",
  ],
  availableNextRound: "available next round",
};
