export const powerUps = {
  settingItUp: "setting it up!",
  yourPowerUps: "your power-ups!",
  seeDetails: "see details",
  useIt: "use it",
  getYourPowerUps: "get your power-ups!",
  theTotalSumOfTheDice: "the total sum of the dice is...",
  timeToWait: "time to wait...",
  waitingTime: "waiting time",
  waitForPlayers: "wait for all the players to roll it!",
  spreadShockwaves: "spread shockwaves",
  playingSmokeAndMirrors: "playing ‘Smoke and mirrors’ to boost your odds of winning",
  playSecondChance: "play ‘Second chance’ to boost your odds of winning. Choose any amount to re-roll!",
  playMenageATrois: "play ‘Ménage à Trois’ to boost your odds of winning",
  feelThePower: "feel the Power",
  playingSecondChance: "we all deserve a second chance. Select any amount of dice and re-roll them.",
  whoIsGoingToGetIt: "who's gonna get it?",
};
