apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # TODO: for staging and prod make it a template, like this "db_password: $DB_PASSWORD", then envsubst in pipeline
  db_password: dGVzdHBhc3N3b3Jk # "testpassword" encoded in base64
