apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    spec:
      containers:
        - name: backend
          image: "eu.gcr.io/web3-335312/aleo/boloney-staging/backend:latest"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONSOLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: console_password
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db_password
            - name: DB_URI
              value: postgres:$(DB_PASSWORD)@postgres.$(POD_NAMESPACE).svc.cluster.local:5432/nakama
            - name: TOOLKIT_BASE_URL
              value: https://zk-gaming-tk.staging.kryha.dev
              # TODO: enable ZK once toolit is deployed on VM
            - name: ZK_ENABLED
              value: "false"
