import { Coup, DoubleUp, Grill, GuardTower, Hypnosis, MenageATrois, SecondChance, SmokeAndMirrors, Vendetta } from "../images";
import { PowerUp, PowerUpId } from "../../types";

export const POWER_UP_DATA: Record<PowerUpId, PowerUp> = {
  "1": {
    id: "1",
    name: "grill",
    shortDescription: "ask an opponent if they have x of y die faces.",
    longDescription: "ask an opponent if they have exactly X number of dice with face value Y.",
    cardImage: Grill,
    isImageLarge: true,
  },
  "2": {
    id: "2",
    name: "bird's Eye View",
    shortDescription: "ask target opponent what the sum of their dice are.",
    longDescription: "ask an opponent the sum of the face values of their dice.",
    cardImage: GuardTower,
    isImageLarge: false,
  },
  "3": {
    id: "3",
    name: "ménage à Trois",
    shortDescription: "roll 3 extra dice to use this turn only.",
    longDescription: "roll 3 extra dice to use this turn only.",
    cardImage: MenageATrois,
    isImageLarge: false,
  },
  "4": {
    id: "4",
    name: "double up",
    shortDescription: "gain 2 power-ups.",
    longDescription: "gain 2 power-ups.",
    cardImage: DoubleUp,
    isImageLarge: true,
  },
  "5": {
    id: "5",
    name: "vendetta",
    shortDescription: "an opponent reveals their hand of cards to you, they can't play cards for the rest of the round.",
    longDescription: "target player reveals their power-ups to you, target player can’t use power-ups for the rest of the round.",
    cardImage: Vendetta,
    isImageLarge: true,
  },
  "6": {
    id: "6",
    name: "second chance",
    shortDescription: "you may re-roll any number of your dice.",
    longDescription: "choose any number of your dice to re-roll.",
    cardImage: SecondChance,
    isImageLarge: false,
  },
  "7": {
    id: "7",
    name: "coup",
    shortDescription: "destroy all your power-ups and gain an equal amount of new power-ups.",
    longDescription: "destroy all your power-ups and gain an equal amount of new power-ups.",
    cardImage: Coup,
    isImageLarge: true,
  },
  "8": {
    id: "8",
    name: "smoke and Mirrors",
    shortDescription: "shuffle the player order and skip your turn.",
    longDescription: "shuffle the player order and skip your turn.",
    cardImage: SmokeAndMirrors,
    isImageLarge: false,
  },
  "9": {
    id: "9",
    name: "hypnosis",
    shortDescription: "target player reveals their power-ups to you, choose one to be transferred to you.",
    longDescription: "target player reveals their power-ups to you, choose one to be transferred to you.",
    cardImage: Hypnosis,
    isImageLarge: true,
  },
};
