apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    spec:
      containers:
        - name: backend
          image: backend
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONSOLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: console_password
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db_password
            - name: DB_URI
              value: postgres:$(DB_PASSWORD)@postgres.$(POD_NAMESPACE).svc.cluster.local:5432/nakama
            - name: ZK_ENABLED
              value: "true"
