apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  template:
    spec:
      containers:
        - name: ui
          image: "localhost:5000/agoric/character-builder/ui:latest"
